[#49] Add optional separate channel for non-error outcomes
massenz/go-statemachine pull request #54
Opened 2022-10-08 22:04 UTC by z-cran

### Ticket
https://github.com/massenz/go-statemachine/issues/49

### Summary of Changes
- Added an optional `outcomes` channel if a `notifications` channel is also provided
  - If `outcomes` is provided, it will receive OK outcomes; `notifications` will receive every other outcome 

### Testing
- Added new unit tests for outcomes & confirmed existing tests pass

2022-10-09 00:02 UTC, massenz requested changes

2022-10-09 00:02 UTC, massenz commented on cmd/main.go
> +			"specified, no outcomes will be published. If an outcomes topic is provided via -outcomes, "+
please move the explanation of what `-outcomes` is in that flag

2022-10-09 00:02 UTC, massenz commented on cmd/main.go
> +	var outcomesTopic = flag.String("outcomes", "",
If I got the gist of this PR right, `outcomes` is only for the positive (OK) results?
the name is confusing here and does not differentiate enough from `notifications`

Please consider using something more descriptive such as `-acks` and make sure the explanations is in a positive, active tense, such as:
```
"If `acks` is specified, all positive outcomes (Ok) will be published here, and only errors will be published to the `notifications` queue"
```

2022-10-09 00:02 UTC, massenz commented on cmd/main.go
> +			"to; if not specified, outcomes will only be published to notifications")
```
"if not specified, all results will published to the -notifications queue, if specified, regardless of their error status"
```

2022-10-09 00:02 UTC, massenz commented on docker/entrypoint.sh
> +OUTCOMES=$([ -n "$OUTCOMES_Q" ] && echo "-outcomes $OUTCOMES_Q" || echo "")
please avoid one-liners "magic" (please observe the Google Shell Style)
honestly, trying to parse this makes my eyes bleed :laughing: 
```
if [[ -n ${OUTCOMES_Q} ]]; then
   whatever
else
  something 
fi
```
or whatever it is that you're trying to do here.
My guess is something like:
```
OUTCOMES=""
if [[ -n ${OUTCOMES_Q} ]]; then
    OUTCOMES="-outcomes ${OUTCOMES_Q}"
fi
```
it's not so terrible, now, is it?

2022-10-09 00:02 UTC, massenz commented on cmd/main.go
> +		if *outcomesTopic != "" {
this is really much more complicated than it needs be IMHO
why not just pass the name of the `outcomes` queue to the SQSPublisher, and leave it up to that bit of code to figure out where to publish `Ok` messages?

That way, you have a single "choke point" and, assume we want to implement support for Kafka (which I really want to do ) or GCP PubSub (which I only marginally want to do) then again, it's just one place.

2022-10-09 00:02 UTC, massenz commented on pubsub/listener.go
> +		if listener.outcomes != nil {
you see? here you have this "castle of ifs" that make reading (and understanding) the code (let alone debugging if anything goes wrong) really complicated - say, three months from now...

Instead in the SQSPub, you just have an if such as:
```
if code == 'ok' && ackTopic != "" {
  send it to ack
  continue
}
send it to notifications
```

2022-10-11 17:54 UTC, z-cran commented
Thanks for the feedback! I moved the logic out of `listener` and into `sub_pub` as recommended and incorporated your other notes (such as in `main` and `entrypoint`).

One note: for the tests, I found I had to add a small sleep between adding an item to a channel & checking the message on the queue. Without this, tests were failing intermittently for me.

2022-10-11 19:44 UTC, z-cran commented
After speaking with @YulyTenorio , we also were hoping to add the capability to provide an empty `-acks` if we did not want Ok outcomes to be published. The PR was updated to incorporate this.

2022-10-12 01:48 UTC, massenz requested changes

2022-10-12 01:48 UTC, massenz commented on README.md
> +  -acks string
this is a nit, but currently the message here and the one in the app do not match

2022-10-12 01:48 UTC, massenz commented on cmd/main.go
> +			"Ok outcomes will not be published. If not specified, all results "+
I don't actually think you can achieve the "specified and not provided a value"?
something like `-ack -foo bar` will assume that the value of `ack` is `-foo` (and the argument `-foo` if required, is missing)

Haven't really tried it, though - have you?
At any rate, I don't like this pattern, as it's confusing.

Please add a boolean `-notify-errors-only` to achieve the same outcome instead (and add a check that it cannot be specified alongside `-ack`)

2022-10-12 01:48 UTC, massenz commented on cmd/main.go
> +			"will published to the `-notifications` queue regardless of their error status")
nit: `will be published`

2022-10-12 01:48 UTC, massenz commented on cmd/main.go
> +func checkForFlag(name string) bool {
this makes the logic really convoluted and very easy to "use it wrong"

2022-10-12 01:48 UTC, massenz commented on pubsub/sqs_pub.go
> +// Publish sends an error message to provided topics
can you please update the docstring to actually reflect what Publish does?

2022-10-12 01:48 UTC, massenz commented on pubsub/sqs_pub.go
> +		queueUrl := GetQueueUrl(s.client, errorsTopic)
please really, really, don't do this
you're looking up the URL for your topic (and it's a full round-trip to AWS management APIs) for *every* message

Please look up and store the queue URL in TWO variables **outside** the `for` loop, and then pick the right one based on (a) is it an OK message and (b) are we publishing Ok messages

2022-10-12 01:48 UTC, massenz commented on pubsub/sqs_pub.go
> +		if acksTopic != "" && !s.ignoreOkOutcomes && eventResponse.Outcome.Code == protos.EventOutcome_Ok {
not to mention, with this logic, you're still publishin on Ok - just to the notification topic (unless I'm missing something)

2022-10-12 01:48 UTC, massenz commented on pubsub/sqs_pub_test.go
> +			time.Sleep(channelWait)
don't do `Sleep` in tests - the pattern to follow is the one used in the other tests, such as in https://github.com/massenz/go-statemachine/blob/main/pubsub/sqs_pub_test.go#L100-L112

2022-10-12 01:48 UTC, massenz commented on pubsub/sqs_pub_test.go
> +			time.Sleep(channelWait)
here too

2022-10-12 01:48 UTC, massenz commented on pubsub/sqs_pub_test.go
> +			res := getSqsMessage(getQueueName(acksQueue))
out of curiousity, you may add a `getSqsMessage` for the `notificationsQueue` and confirm whether it gets the ok message (which I think it does with current code); you need to check them both anyway and confirm we drop those

2022-10-12 18:35 UTC, massenz approved these changes

2022-10-12 20:10 UTC, merged